* [WIP] MPV Redirector
MPV Redirector is a simple script to redirect video urls to mpv using yt-dlp.

** Install
Run ~make install~ from the root of this repository. By default the script uses ~$HOME/.local~ as a prefix but if you want to install to a different location you can use ~make PREFIX=/your/prefix/dir install~ to install to a different directory. For example, you can run ~make PREFIX=/usr/local install~ to install the script to ~/usr/local/bin~ instead of the default.
*** NOTE
Do *NOT* use ~sudo~, ~doas~, ~pkexec~, or any other privilege escalation command to run make. Our make install target assumes the .desktop file goes into the home directory of a normal user and not in ~/root~. This is a bug that may get fixed at one point, but don't install the script with privilege escalation until this problem is fixed.
** Uninstall
Run ~make uninstall~ to uninstall the files from your system, specifying the prefix as shown above if you use a non-default path.
** Dependencies
+ bash (don't know how to do arrays in posix-compliant shell)
+ fzf
+ gtk-launch (the plan is to support a variety of desktop launchers, and fall back to our own implementation if none are found, but this is what we require for now).
+ mpv
+ yt-dlp
** How to use
If you wish to use this as a way to intercept URL queries before they reach your browser, simply set mpv-redirector as your default browser from within gnome or kde settings (or the settings of whatever desktop environment you use). The Makefile adds a .desktop entry to your ~$HOME/.local/share/applications/~ directory so you can use it from the GUI to automatically throw videos into mpv or display them on your browser if it's not a video site. The script will run a first-time setup if it doesn't detect an existing configuration at ~$HOME/.config/mpv-redirector/config.sh~ and it will just ask which browser you prefer to launch non-video urls in.
*** First time setup
The script contains a first time setup if a config file isn't detected at ~$XDG_CONFIG_HOME/.config/mpv-redirector.sh~, the first-time setup is barebones for now, with only an fzf window to choose the preferred browser to launch non-video urls in.jk
** TODOs
*** TODO Add a way to configure quality and pass that into yt-dlp, and add that configured quality to ~$XDG_CONFIG_HOME/mpv-redirector/config.sh~
**** TODO Add configuration option for default quality into the first-time setup
*** TODO Support multiple backends for launching .desktop files, degrading to our own if none are installed.
**** TODO Maybe add a preferred backend for users to configure
*** TODO Prevent ~make install~ from being run using privilege escalation (~sudo~, ~doas~, ~pkexec~, etc.), or detect privilege escalation and put the .desktop file in the right place (if using root privs it would be ~/usr/share/applications~).
*** TODO Add extra information to fzf windows when running first time setup, such as what you're configuring.
*** TODO Add optional whitelisting of domains, so only specific ones are sent to yt-dlp (there are some websites where mpv will play a video embedded on the website where it's just a small part of an article)
